print('TABUADA DE UM NÚMERO')
numero = int(input('Digite um número: '))
print(f'{numero} x 1  = {numero}')
print(f'{numero} x 2  = {numero*2}')
print(f'{numero} x 3  = {numero*3}')
print(f'{numero} x 4  = {numero*4}')
print(f'{numero} x 5  = {numero*5}')
print(f'{numero} x 6  = {numero*6}')
print(f'{numero} x 7  = {numero*7}')
print(f'{numero} x 8  = {numero*8}')
print(f'{numero} x 9  = {numero*9}')
print(f'{numero} x 10  = {numero*10}')
