valor = input('Digite alguma coisa: ')
print(f'Foi digitado: {valor}')
print(f'É do tipo: {type(valor)}')
print(f'É um Alfa-Numerico: {valor.isalnum()}')
print(f'É constituido apenas por caracteres: {valor.isalpha()}')
print(f'Pode ser convertido para número: {valor.isnumeric()}')
print(f'Está em letras maiusculas: {valor.isupper()}')
print(f'Está em letras minusculas: {valor.islower()}')
print(f'É um espaço: {valor.isspace()}')
print(f'É um valor decimal: {valor.isdecimal()}')
print(f'É apenas um digito: {valor.isdigit()}')
print(f'É composto por letras maiusculas no Inicio e Minusculas: {valor.istitle()}')
print(f'É ASCII: {valor.isascii()}')
